name = "o4wb3c"
version = "0.1.0"
license = "license"
author = "Marcel Mueller"
maintainer = "marcel.mueller@thch.uni-bonn.de"
copyright = "Copyright 2023, Marcel Mueller"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[dependencies]
mctc-lib.git = "https://github.com/grimme-lab/mctc-lib"
stdlib = "*"
